drop database if exists monumentsparis;
create database monumentsparis;

DROP TABLE IF EXISTS monuments ;
CREATE TABLE monuments 
(
	id_monuments INT(5) AUTO_INCREMENT NOT NULL,
	nom_monuments VARCHAR(50),
	id_metro INT(2),
	id_arrondissement INT(2),
	PRIMARY KEY (id_monuments)
);

DROP TABLE IF EXISTS metro ;
CREATE TABLE metro 
(
	id_metro INT(2) AUTO_INCREMENT NOT NULL,
	station_metro VARCHAR(100),
	lignes_metro VARCHAR(2),
	PRIMARY KEY (id_metro)
);

DROP TABLE IF EXISTS arrondissement ;
CREATE TABLE arrondissement 
(
	id_arrondissement INT(2) AUTO_INCREMENT NOT NULL,
	numero_arrondissement VARCHAR(5),
	PRIMARY KEY (id_arrondissement)
);

ALTER TABLE monuments ADD CONSTRAINT id_metro FOREIGN KEY (id_metro) REFERENCES metro (id_metro);
ALTER TABLE monuments ADD CONSTRAINT id_arrondissement FOREIGN KEY (id_arrondissement) REFERENCES arrondissement (id_arrondissement);

INSERT INTO metro(station_metro, lignes_metro) VALUES
('La Défense - Grande Arche', '1'),	
('Pont de Neuilly', '1'),	
('Les Sablons', '1'),	
('Porte Maillot - Palais des Congrès', '1'),
('Charles de Gaulle — Étoile', '1'),
('George V', '1'),
('Franklin D. Roosevelt', '1'),
('Champs-Élysées — Clemenceau', '1'),
('Concorde', '1'),
('Tuileries', '1'),	
('Palais Royal - Musée du Louvre', '1'),
('Louvre — Rivoli', '1'),	
('Châtelet', '1'),
('Hôtel de Ville', '1'),
('Saint-Paul', '1'),	
('Bastille', '1'),
('Gare de Lyon', '1'),
('Reuilly — Diderot', '1'),
('Nation', '1'),
('Porte de Vincennes', '1'),
('Saint-Mandé', '1'),
('Bérault', '1'),
('Château de Vincennes', '1'),
('Victor Hugo', '2'),	
('Charles de Gaulle — Étoile', '2'),
('Ternes', '2'),
('Courcelles', '2'),
('Monceau', '2'),
('Villiers', '2'),
('Rome', '2'),
('Place de Clichy', '2'),
('Blanche', '2'),
('Pigalle', '2'),
('Anvers', '2'),
('Barbès — Rochechouart', '2'),
('La Chapelle', '2'),
('Gare du Nord', '2'),
('Stalingrad', '2'),
('Jaurès', '2'),
('Colonel Fabien', '2'),
('Belleville', '2'),
('Couronnes', '2'),
('Ménilmontant', '2'),
('Père Lachaise', '2'),
('Philippe Auguste', '2'),
('Alexandre Dumas', '2'),
('Avron', '2'),
('Nation', '2'),
('Pont de Levallois — Bécon', '3'),
('Anatole France', '3'),
('Louise Michel', '3'),
('Porte de Champerret', '3'),
('Pereire (Maréchal Juin)', '3'),
('Wagram', '3'),
('Malesherbes', '3'),
('Villiers', '3'),
('Europe', '3'),
('Saint-Lazare', '3'),
('Havre — Caumartin', '3'),
('Opéra', '3'),
('Quatre-Septembre', '3'),
('Bourse', '3'),
('Sentier', '3'),
('Réaumur — Sébastopol', '3'),
('Arts et Métiers', '3'),
('Temple', '3'),
('République', '3'),
('Parmentier', '3'),
('Rue Saint-Maur', '3'),
('Père Lachaise', '3'),
('Gambetta', '3'),
('Porte de Bagnolet', '3'),
('Gallieni (Parc de Bagnolet)', '3'),
('Porte des Lilas	', '3bis'),
('Saint-Fargeau	', '3bis'),
('Pelleport', '3bis'),
('Gambetta', '3bis'),
('Porte de Clignancourt', '4'),
('Simplon', '4'),
('Marcadet — Poissonniers', '4'),
('Château Rouge', '4'),
('Barbès — Rochechouart', '4'),
('Gare du Nord', '4'),
("Gare de l'Est (Verdun)", '4'),
("Château d'Eau", '4'),
('Strasbourg — Saint-Denis', '4'),
('Réaumur — Sébastopol', '4'),
('Étienne Marcel', '4'),
('Les Halles', '4'),
('Châtelet', '4'),
('Cité', '4'),
('Saint-Michel', '4'),
('Odéon', '4'),
('Saint-Germain-des-Prés', '4'),
('Saint-Sulpice', '4'),
('Saint-Placide', '4'),
('Montparnasse — Bienvenüe', '4'),
('Vavin', '4'),
('Raspail', '4'),
('Denfert-Rochereau (Colonel Rol-Tanguy)', '4'),
('Mouton-Duvernet', '4'),
('Alésia', '4'),
("Porte d'Orléans (Général Leclerc)", '4'),
('Mairie de Montrouge', '5'),
('Bobigny - Pablo Picasso', '5'),
('Bobigny — Pantin — Raymond Queneau', '5'),
('Église de Pantin', '5'),
('Hoche', '5'),
('Porte de Pantin (Parc de la Villette)', '5'),
('Ourcq', '5'),
('Laumière', '5'),
('Jaurès', '5'),
('Stalingrad', '5'),
('Gare du Nord', '5'),
("Gare de l'Est (Verdun)", '5'),
('Jacques Bonsergent', '5'),
('République', '5'),
('Oberkampf', '5'),
('Richard-Lenoir', '5'),
('Bréguet — Sabin', '5'),
('Bastille', '5'),
('Quai de la Rapée', '5'),
("Gare d'Austerlitz", '5'),
('Saint-Marcel', '5'),
('Campo-Formio', '5'),
("Place d'Italie", '5'),
('Charles de Gaulle — Étoile', '6'),
('Kléber', '6'),
('Boissière', '6'),
('Trocadéro', '6'),
('Passy', '6'),
('Bir-Hakeim (Tour Eiffel)', '6'),
('Dupleix', '6'),
('La Motte-Picquet — Grenelle	', '6'),
('Cambronne', '6'),
('Sèvres — Lecourbe', '6'),
('Pasteur', '6'),
('Montparnasse — Bienvenüe', '6'),
('Edgar Quinet', '6'),
('Raspail', '6'),
('Denfert-Rochereau', '6'),
('Saint-Jacques', '6'),
('Glacière', '6'),
('Corvisart', '6'),
("Place d'Italie", '6'),
('Nationale', '6'),
('Chevaleret', '6'),
('Quai de la Gare', '6'),
('Bercy', '6'),
('Dugommier', '6'),
('Daumesnil (Félix Éboué)', '6'),
('Bel-Air', '6'),
('Picpus (Courteline)', '6'),
('Nation', '6'),
('La Courneuve — 8 Mai 1945', '7'),
("Fort d'Aubervilliers", '7'),
('Aubervilliers — Pantin — Quatre Chemins', '7'),
("Porte de la Villette (Cité des Sciences et de l'Industrie)", '7'),
('Corentin Cariou', '7'),
('Crimée', '7'),
('Riquet', '7'),
('Stalingrad', '7'),
('Louis Blanc', '7'),
('Château-Landon', '7'),
("Gare de l'Est (Verdun)", '7'),
('Poissonnière', '7'),
('Cadet', '7'),
('Le Peletier', '7'),
("Chaussée d'Antin — La Fayette", '7'),
('Opéra', '7'),
('Pyramides', '7'),
('Palais Royal — Musée du Louvre', '7'),
('Pont Neuf', '7'),
('Châtelet', '7'),
('Pont Marie (Cité des Arts)', '7'),
('Sully — Morland', '7'),
('Jussieu', '7'),
('Place Monge (Jardin des Plantes - Arènes de Lutèce)', '7'),
('Censier — Daubenton', '7'),
('Les Gobelins', '7'),
("Place d'Italie", '7'),
('Tolbiac', '7'),
('Maison Blanche', '7'),
("Porte d'Italie Tramway T3", '7'),
("Porte de Choisy Tramway T3", '7'),
("Porte d'Ivry Tramway T3", '7'),
('Pierre et Marie Curie', '7'),
("Mairie d'Ivry", '7'),
('Louis Blanc', '7bis'),
('Jaurès', '7bis'),
('Bolivar', '7bis'),
('Buttes Chaumont	', '7bis'),
('Botzaris', '7bis'),
('Place des Fêtes', '7bis'),
('Danube', '7bis'),
('Pré Saint-Gervais', '7bis'),
('Balard', '8'),
('Lourmel', '8'),
('Boucicaut', '8'),
('Félix Faure', '8'),
('Commerce', '8'),
('La Motte-Picquet — Grenelle', '8'),
('École Militaire', '8'),
('La Tour-Maubourg', '8'),
('Invalides', '8'),
('Concorde', '8'),
('Madeleine', '8'),
('Opéra', '8'),
('Richelieu — Drouot', '8'),
('Grands Boulevards', '8'),
('Bonne Nouvelle', '8'),
('Strasbourg — Saint-Denis', '8'),
('République', '8'),
('Filles du Calvaire', '8'),
('Saint-Sébastien — Froissart', '8'),
('Chemin Vert', '8'),
('Bastille', '8'),
('Ledru-Rollin', '8'),
('Faidherbe — Chaligny', '8'),
('Reuilly — Diderot', '8'),
('Montgallet', '8'),
('Daumesnil (Félix Éboué)', '8'),
('Michel Bizot', '8'),
('Porte Dorée', '8'),
('Porte de Charenton', '8'),
('Liberté', '8'),
('Charenton — Écoles (Place Aristide Briand)	', '8'),
('École Vétérinaire de Maisons-Alfort', '8'),
('Maisons-Alfort — Stade', '8'),
('Maisons-Alfort — Les Juilliottes', '8'),
("Créteil — L'Échat (Hôpital Henri Mondor)", '8'),
('Créteil — Université', '8'),
('Créteil — Préfecture (Hôtel de Ville)', '8'),
('Pont de Sèvres', '9'),
('Billancourt', '9'),
('Marcel Sembat', '9'),
('Porte de Saint-Cloud (Parc des Princes)', '9'),
('Exelmans', '9'),
('Michel-Ange — Molitor', '9'),
('Michel-Ange — Auteuil', '9'),
('Jasmin', '9'),
('Ranelagh', '9'),
('La Muette', '9'),
('Rue de la Pompe (Avenue Georges Mandel)	', '9'),
('Trocadéro', '9'),
('Iéna', '9'),
('Alma — Marceau', '9'),
('Franklin D. Roosevelt', '9'),
('Saint-Philippe du Roule', '9'),
('Miromesnil', '9'),
('Saint-Augustin', '9'),
('Havre — Caumartin', '9'),
("Chaussée d'Antin — La Fayette", '9'),
('Richelieu — Drouot', '9'),
('Grands Boulevards', '9'),
('Bonne Nouvelle', '9'),
('Strasbourg — Saint-Denis', '9'),
('République', '9'),
('Oberkampf', '9'),
('Saint-Ambroise', '9'),
('Voltaire (Léon Blum)', '9'),
('Charonne', '9'),
('Rue des Boulets', '9'),
('Nation', '9'),
('Buzenval', '9'),
('Maraîchers', '9'),
('Porte de Montreuil', '9'),
('Robespierre', '9'),
('Croix de Chavaux (Place Jacques Duclos)', '9'),
('Mairie de Montreuil', '9'),
('Boulogne — Pont de Saint-Cloud (Rhin et Danube)', '10'),
('Boulogne — Jean Jaurès', '10'),
('Michel-Ange — Molitor', '10'),
('Chardon-Lagache', '10'),
('Mirabeau', '10'),
("Porte d'Auteuil", '10'),
('Michel-Ange — Auteuil', '10'),
("Église d'Auteuil", '10'),
('Javel — André Citroën', '10'),
('Charles Michels', '10'),
('Avenue Émile Zola', '10'),
('La Motte-Picquet — Grenelle', '10'),
('Ségur', '10'),
('Duroc', '10'),
('Vaneau', '10'),
('Sèvres — Babylone', '10'),
('Mabillon', '10'),
('Odéon', '10'),
('Cluny — La Sorbonne', '10'),
('Maubert — Mutualité', '10'),
('Cardinal Lemoine', '10'),
('Jussieu', '10'),
("Gare d'Austerlitz", '10'),
('Mairie des Lilas', '11'),
('Porte des Lilas', '11'),
('Télégraphe', '11'),
('Place des Fêtes', '11'),
('Jourdain', '11'),
('Pyrénées', '11'),
('Belleville', '11'),
('Goncourt (Hôpital-Saint-Louis)', '11'),
('République', '11'),
('Arts et Métiers', '11'),
('Rambuteau (Centre Georges Pompidou)', '11'),
('Hôtel de Ville', '11'),
('Châtelet', '11'),
('Porte de la Chapelle', '12'),
('Marx Dormoy', '12'),
('Marcadet — Poissonniers', '12'),
('Jules Joffrin', '12'),
('Lamarck — Caulaincourt', '12'),
('Abbesses (Butte Montmartre)', '12'),
('Pigalle', '12'),
('Saint-Georges', '12'),
('Notre-Dame-de-Lorette', '12'),
("Trinité — d'Estienne d'Orves", '12'),
('Saint-Lazare', '12'),
('Madeleine', '12'),
('Concorde', '12'),
('Assemblée nationale', '12'),
("Solférino (Musée d'Orsay)", '12'),
('Rue du Bac', '12'),
('Sévres — Babylone', '12'),
('Rennes', '12'),
('Notre-Dame-des-Champs', '12'),
('Montparnasse — Bienvenüe', '12'),
('Falguière', '12'),
('Pasteur', '12'),
('Volontaires', '12'),
('Vaugirard (Adolphe Chérioux)', '12'),
('Convention', '12'),
('Porte de Versailles (Parc des Expositions de Paris)', '12'),
('Corentin Celton', '12'),
("Mairie d'Issy", '12'),
('Saint-Denis - Université', '13'),
('Basilique de Saint-Denis (Hôtel de Ville)', '13'),
('Saint-Denis - Porte de Paris (Stade de France)', '13'),
('Carrefour Pleyel', '13'),
('Mairie de Saint-Ouen', '13'),
('Garibaldi', '13'),
('Porte de Saint-Ouen', '13'),
('Guy Môquet', '13'),
('Gabriel Péri - Asnières - Gennevilliers', '13'),
('Mairie de Clichy', '13'),
('Porte de Clichy', '13'),
('Brochant', '13'),
('La Fourche', '13'),
('Place de Clichy', '13'),
('Liège', '13'),
('Saint-Lazare', '13'),
('Miromesnil', '13'),
('Champs-Élysées — Clemenceau (Grand Palais)', '13'),
('Invalides', '13'),
('Varenne', '13'),
('Saint-François-Xavier', '13'),
('Duroc', '13'),
('Montparnasse — Bienvenüe', '13'),
('Gaîté', '13'),
('Pernety', '13'),
('Plaisance', '13'),
('Porte de Vanves', '13'),
('Malakoff — Plateau de Vanves', '13'),
('Malakoff — Rue Étienne Dolet', '13'),
('Châtillon — Montrouge', '13'),
('Saint-Lazare', '14'),
('Madeleine', '14'),
('Pyramides', '14'),
('Châtelet', '14'),
('Gare de Lyon', '14'),
('Bercy', '14'),
('Cour Saint-Émilion', '14'),
('Bibliothèque François Mitterrand', '14'),
('Olympiades', '14');


INSERT INTO arrondissement( numero_arrondissement) VALUES
('75001'),
('75002'),
('75003'),
('75004'),
('75005'),
('75006'),
('75007'),
('75008'),
('75009'),
('75010'),
('75011'),
('75012'),
('75013'),
('75014'),
('75015'),
('75016'),
('75017'),
('75018'),
('75019'),
('75020');

INSERT INTO monuments(nom_monuments, id_metro, id_arrondissement) VALUES
('La tour Eiffel', 25, 4),
('Conciergerie', 91, 1),
('Centre Pompidou',304, 4),
('Sainte-Chapelle', 91, 1),
("Musée d'Orsay", 321, 7),
('Panthéon', 290, 5),
('Arc de Triomphe', , 8),
('Musée du quai Branly', '', 7),
('Jardin des Tuileries', '', 1),
('Institut du monde arabe', '', 5),
('Grand Palais', '', 5),
('Petit Palais - Musée des Beaux-Arts de la ville de Paris', '', 8),
('Hôtel de Ville de Paris', '', 4),
('Musée Rodin Paris', '', 7),
('Cathédrale Notre-Dame de Paris et son trésor', '', 4),
('Basilique du Sacré-Coeur de Montmartre', '', 18),
("Avenue des Champs-Élysées", '', 8),
("Tour Saint-Jacques", '', 1),
("Île de la Cité", '', 4),
("Gare du Nord", '', 10),
("Gare de l'Est", '', 10),
("Cirque d'Hiver Bouglione", '', 11),
("Cathédrale de la Sainte-Trinité - Église Orthodoxe Russe", '', 7),
("Centre Bouddhique Kagyu-Dzong - Grande Pagode de Vincennes", '', 12),
("Place de la Concorde", '', 8),
("Musée de Cluny - Le monde médiéval", '', 5),
("Tour Jean-sans-Peur", '', 2),
("Arènes de Lutèce et square Capitan", '', 5),
('Musée du Louvre', '', 1),
('Opéra national de Paris - Palais Garnier', '', 9),
('tour Paris Montparnasse', '', 15),
('Cimetière du Père Lachaise', '', 20),
("Musée de l'Orangerie", "", 1);
